name: Deploying To Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/secret.pem
          chmod 600 ~/secret.pem
          ssh -i "~/secret.pem" ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} '
            pm2 stop all
            cd Stayfit-Backend 
            git fetch 
            git reset --hard origin/main
            pm2 restart all'
