name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: .env
    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate SSH key and Deploy
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/secret.pem
          chmod 600 ~/secret.pem
          ssh -o StrictHostKeyChecking=no -i "~/secret.pem" ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} '
            pm2 stop all
            cd Stayfit-Backend 
            git fetch 
            git reset --hard origin/main
            pm2 restart all'
